# Generated by Django 6.0.7 on 2026-08-03 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_remove_course_category_course_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('course_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_cart_object', to='courses.course')),
                ('student_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_cart_object', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('course_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_wishlist_object', to='courses.course')),
                ('student_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_wishlist_object', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
