# Generated by Django 6.0.7 on 2026-08-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='trail_object',
            new_name='course_object',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='hiker_object',
            new_name='student_object',
        ),
    ]
